/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.analysis;

import java.util.*;
import org.linguate.arboratecompiler.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        {
            List<PFuncDecl> copy = new ArrayList<PFuncDecl>(node.getFunctions());
            Collections.reverse(copy);
            for(PFuncDecl e : copy)
            {
                e.apply(this);
            }
        }
        outAProgram(node);
    }

    public void inAFuncDecl(AFuncDecl node)
    {
        defaultIn(node);
    }

    public void outAFuncDecl(AFuncDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDecl(AFuncDecl node)
    {
        inAFuncDecl(node);
        {
            List<PStatement> copy = new ArrayList<PStatement>(node.getStatement());
            Collections.reverse(copy);
            for(PStatement e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getFuncDeclArgList() != null)
        {
            node.getFuncDeclArgList().apply(this);
        }
        if(node.getFuncDeclName() != null)
        {
            node.getFuncDeclName().apply(this);
        }
        outAFuncDecl(node);
    }

    public void inAFuncDeclArgList(AFuncDeclArgList node)
    {
        defaultIn(node);
    }

    public void outAFuncDeclArgList(AFuncDeclArgList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDeclArgList(AFuncDeclArgList node)
    {
        inAFuncDeclArgList(node);
        {
            List<PFuncDeclArg> copy = new ArrayList<PFuncDeclArg>(node.getFuncDeclArg());
            Collections.reverse(copy);
            for(PFuncDeclArg e : copy)
            {
                e.apply(this);
            }
        }
        outAFuncDeclArgList(node);
    }

    public void inAFuncDeclArg(AFuncDeclArg node)
    {
        defaultIn(node);
    }

    public void outAFuncDeclArg(AFuncDeclArg node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDeclArg(AFuncDeclArg node)
    {
        inAFuncDeclArg(node);
        if(node.getFuncDeclArgName() != null)
        {
            node.getFuncDeclArgName().apply(this);
        }
        if(node.getFuncDeclArgType() != null)
        {
            node.getFuncDeclArgType().apply(this);
        }
        outAFuncDeclArg(node);
    }

    public void inADeclarationStatement(ADeclarationStatement node)
    {
        defaultIn(node);
    }

    public void outADeclarationStatement(ADeclarationStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclarationStatement(ADeclarationStatement node)
    {
        inADeclarationStatement(node);
        if(node.getVarDeclName() != null)
        {
            node.getVarDeclName().apply(this);
        }
        if(node.getVarDeclType() != null)
        {
            node.getVarDeclType().apply(this);
        }
        outADeclarationStatement(node);
    }

    public void inAAssignmentStatement(AAssignmentStatement node)
    {
        defaultIn(node);
    }

    public void outAAssignmentStatement(AAssignmentStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignmentStatement(AAssignmentStatement node)
    {
        inAAssignmentStatement(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getVarAssignName() != null)
        {
            node.getVarAssignName().apply(this);
        }
        outAAssignmentStatement(node);
    }

    public void inAReturnStatement(AReturnStatement node)
    {
        defaultIn(node);
    }

    public void outAReturnStatement(AReturnStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReturnStatement(AReturnStatement node)
    {
        inAReturnStatement(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAReturnStatement(node);
    }

    public void inAAddExpr(AAddExpr node)
    {
        defaultIn(node);
    }

    public void outAAddExpr(AAddExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAddExpr(AAddExpr node)
    {
        inAAddExpr(node);
        if(node.getOp2() != null)
        {
            node.getOp2().apply(this);
        }
        if(node.getOp1() != null)
        {
            node.getOp1().apply(this);
        }
        outAAddExpr(node);
    }

    public void inASubtractExpr(ASubtractExpr node)
    {
        defaultIn(node);
    }

    public void outASubtractExpr(ASubtractExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtractExpr(ASubtractExpr node)
    {
        inASubtractExpr(node);
        if(node.getOp2() != null)
        {
            node.getOp2().apply(this);
        }
        if(node.getOp1() != null)
        {
            node.getOp1().apply(this);
        }
        outASubtractExpr(node);
    }

    public void inAMultiplyExpr(AMultiplyExpr node)
    {
        defaultIn(node);
    }

    public void outAMultiplyExpr(AMultiplyExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplyExpr(AMultiplyExpr node)
    {
        inAMultiplyExpr(node);
        if(node.getOp2() != null)
        {
            node.getOp2().apply(this);
        }
        if(node.getOp1() != null)
        {
            node.getOp1().apply(this);
        }
        outAMultiplyExpr(node);
    }

    public void inADivideExpr(ADivideExpr node)
    {
        defaultIn(node);
    }

    public void outADivideExpr(ADivideExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivideExpr(ADivideExpr node)
    {
        inADivideExpr(node);
        if(node.getOp2() != null)
        {
            node.getOp2().apply(this);
        }
        if(node.getOp1() != null)
        {
            node.getOp1().apply(this);
        }
        outADivideExpr(node);
    }

    public void inAIntLitValue(AIntLitValue node)
    {
        defaultIn(node);
    }

    public void outAIntLitValue(AIntLitValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntLitValue(AIntLitValue node)
    {
        inAIntLitValue(node);
        if(node.getIntString() != null)
        {
            node.getIntString().apply(this);
        }
        outAIntLitValue(node);
    }

    public void inAFuncCallValue(AFuncCallValue node)
    {
        defaultIn(node);
    }

    public void outAFuncCallValue(AFuncCallValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCallValue(AFuncCallValue node)
    {
        inAFuncCallValue(node);
        if(node.getFuncCallArgList() != null)
        {
            node.getFuncCallArgList().apply(this);
        }
        if(node.getFuncCallName() != null)
        {
            node.getFuncCallName().apply(this);
        }
        outAFuncCallValue(node);
    }

    public void inAVarFetchValue(AVarFetchValue node)
    {
        defaultIn(node);
    }

    public void outAVarFetchValue(AVarFetchValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarFetchValue(AVarFetchValue node)
    {
        inAVarFetchValue(node);
        if(node.getVarFetchName() != null)
        {
            node.getVarFetchName().apply(this);
        }
        outAVarFetchValue(node);
    }

    public void inAFuncCallArgList(AFuncCallArgList node)
    {
        defaultIn(node);
    }

    public void outAFuncCallArgList(AFuncCallArgList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCallArgList(AFuncCallArgList node)
    {
        inAFuncCallArgList(node);
        {
            List<PFuncCallArg> copy = new ArrayList<PFuncCallArg>(node.getFuncCallArg());
            Collections.reverse(copy);
            for(PFuncCallArg e : copy)
            {
                e.apply(this);
            }
        }
        outAFuncCallArgList(node);
    }

    public void inAFuncCallArg(AFuncCallArg node)
    {
        defaultIn(node);
    }

    public void outAFuncCallArg(AFuncCallArg node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCallArg(AFuncCallArg node)
    {
        inAFuncCallArg(node);
        if(node.getValue() != null)
        {
            node.getValue().apply(this);
        }
        outAFuncCallArg(node);
    }

    public void inAFuncDeclName(AFuncDeclName node)
    {
        defaultIn(node);
    }

    public void outAFuncDeclName(AFuncDeclName node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDeclName(AFuncDeclName node)
    {
        inAFuncDeclName(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAFuncDeclName(node);
    }

    public void inAFuncDeclArgType(AFuncDeclArgType node)
    {
        defaultIn(node);
    }

    public void outAFuncDeclArgType(AFuncDeclArgType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDeclArgType(AFuncDeclArgType node)
    {
        inAFuncDeclArgType(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAFuncDeclArgType(node);
    }

    public void inAFuncDeclArgName(AFuncDeclArgName node)
    {
        defaultIn(node);
    }

    public void outAFuncDeclArgName(AFuncDeclArgName node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncDeclArgName(AFuncDeclArgName node)
    {
        inAFuncDeclArgName(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAFuncDeclArgName(node);
    }

    public void inAFuncCallName(AFuncCallName node)
    {
        defaultIn(node);
    }

    public void outAFuncCallName(AFuncCallName node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCallName(AFuncCallName node)
    {
        inAFuncCallName(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAFuncCallName(node);
    }

    public void inAVarDeclType(AVarDeclType node)
    {
        defaultIn(node);
    }

    public void outAVarDeclType(AVarDeclType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDeclType(AVarDeclType node)
    {
        inAVarDeclType(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAVarDeclType(node);
    }

    public void inAVarDeclName(AVarDeclName node)
    {
        defaultIn(node);
    }

    public void outAVarDeclName(AVarDeclName node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDeclName(AVarDeclName node)
    {
        inAVarDeclName(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAVarDeclName(node);
    }

    public void inAVarAssignName(AVarAssignName node)
    {
        defaultIn(node);
    }

    public void outAVarAssignName(AVarAssignName node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarAssignName(AVarAssignName node)
    {
        inAVarAssignName(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAVarAssignName(node);
    }

    public void inAVarFetchName(AVarFetchName node)
    {
        defaultIn(node);
    }

    public void outAVarFetchName(AVarFetchName node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarFetchName(AVarFetchName node)
    {
        inAVarFetchName(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAVarFetchName(node);
    }
}
