/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class ABoolLitExpr extends PExpr
{
    private TBoolString _boolString_;

    public ABoolLitExpr()
    {
        // Constructor
    }

    public ABoolLitExpr(
        @SuppressWarnings("hiding") TBoolString _boolString_)
    {
        // Constructor
        setBoolString(_boolString_);

    }

    @Override
    public Object clone()
    {
        return new ABoolLitExpr(
            cloneNode(this._boolString_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolLitExpr(this);
    }

    public TBoolString getBoolString()
    {
        return this._boolString_;
    }

    public void setBoolString(TBoolString node)
    {
        if(this._boolString_ != null)
        {
            this._boolString_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolString_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolString_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolString_ == child)
        {
            this._boolString_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolString_ == oldChild)
        {
            setBoolString((TBoolString) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
