/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import java.util.*;
import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncDecl extends PFuncDecl
{
    private PFuncDeclRetType _funcDeclRetType_;
    private PFuncDeclName _funcDeclName_;
    private PFuncDeclArgList _funcDeclArgList_;
    private final LinkedList<PStatement> _statement_ = new LinkedList<PStatement>();

    public AFuncDecl()
    {
        // Constructor
    }

    public AFuncDecl(
        @SuppressWarnings("hiding") PFuncDeclRetType _funcDeclRetType_,
        @SuppressWarnings("hiding") PFuncDeclName _funcDeclName_,
        @SuppressWarnings("hiding") PFuncDeclArgList _funcDeclArgList_,
        @SuppressWarnings("hiding") List<?> _statement_)
    {
        // Constructor
        setFuncDeclRetType(_funcDeclRetType_);

        setFuncDeclName(_funcDeclName_);

        setFuncDeclArgList(_funcDeclArgList_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AFuncDecl(
            cloneNode(this._funcDeclRetType_),
            cloneNode(this._funcDeclName_),
            cloneNode(this._funcDeclArgList_),
            cloneList(this._statement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncDecl(this);
    }

    public PFuncDeclRetType getFuncDeclRetType()
    {
        return this._funcDeclRetType_;
    }

    public void setFuncDeclRetType(PFuncDeclRetType node)
    {
        if(this._funcDeclRetType_ != null)
        {
            this._funcDeclRetType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDeclRetType_ = node;
    }

    public PFuncDeclName getFuncDeclName()
    {
        return this._funcDeclName_;
    }

    public void setFuncDeclName(PFuncDeclName node)
    {
        if(this._funcDeclName_ != null)
        {
            this._funcDeclName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDeclName_ = node;
    }

    public PFuncDeclArgList getFuncDeclArgList()
    {
        return this._funcDeclArgList_;
    }

    public void setFuncDeclArgList(PFuncDeclArgList node)
    {
        if(this._funcDeclArgList_ != null)
        {
            this._funcDeclArgList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDeclArgList_ = node;
    }

    public LinkedList<PStatement> getStatement()
    {
        return this._statement_;
    }

    public void setStatement(List<?> list)
    {
        for(PStatement e : this._statement_)
        {
            e.parent(null);
        }
        this._statement_.clear();

        for(Object obj_e : list)
        {
            PStatement e = (PStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._statement_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcDeclRetType_)
            + toString(this._funcDeclName_)
            + toString(this._funcDeclArgList_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcDeclRetType_ == child)
        {
            this._funcDeclRetType_ = null;
            return;
        }

        if(this._funcDeclName_ == child)
        {
            this._funcDeclName_ = null;
            return;
        }

        if(this._funcDeclArgList_ == child)
        {
            this._funcDeclArgList_ = null;
            return;
        }

        if(this._statement_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcDeclRetType_ == oldChild)
        {
            setFuncDeclRetType((PFuncDeclRetType) newChild);
            return;
        }

        if(this._funcDeclName_ == oldChild)
        {
            setFuncDeclName((PFuncDeclName) newChild);
            return;
        }

        if(this._funcDeclArgList_ == oldChild)
        {
            setFuncDeclArgList((PFuncDeclArgList) newChild);
            return;
        }

        for(ListIterator<PStatement> i = this._statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
