/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import java.util.*;
import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncCallArgList extends PFuncCallArgList
{
    private final LinkedList<PFuncCallArg> _funcCallArg_ = new LinkedList<PFuncCallArg>();

    public AFuncCallArgList()
    {
        // Constructor
    }

    public AFuncCallArgList(
        @SuppressWarnings("hiding") List<?> _funcCallArg_)
    {
        // Constructor
        setFuncCallArg(_funcCallArg_);

    }

    @Override
    public Object clone()
    {
        return new AFuncCallArgList(
            cloneList(this._funcCallArg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncCallArgList(this);
    }

    public LinkedList<PFuncCallArg> getFuncCallArg()
    {
        return this._funcCallArg_;
    }

    public void setFuncCallArg(List<?> list)
    {
        for(PFuncCallArg e : this._funcCallArg_)
        {
            e.parent(null);
        }
        this._funcCallArg_.clear();

        for(Object obj_e : list)
        {
            PFuncCallArg e = (PFuncCallArg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._funcCallArg_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcCallArg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcCallArg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PFuncCallArg> i = this._funcCallArg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFuncCallArg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
