/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import java.util.*;
import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncDeclArgList extends PFuncDeclArgList
{
    private final LinkedList<PFuncDeclArg> _funcDeclArg_ = new LinkedList<PFuncDeclArg>();

    public AFuncDeclArgList()
    {
        // Constructor
    }

    public AFuncDeclArgList(
        @SuppressWarnings("hiding") List<?> _funcDeclArg_)
    {
        // Constructor
        setFuncDeclArg(_funcDeclArg_);

    }

    @Override
    public Object clone()
    {
        return new AFuncDeclArgList(
            cloneList(this._funcDeclArg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncDeclArgList(this);
    }

    public LinkedList<PFuncDeclArg> getFuncDeclArg()
    {
        return this._funcDeclArg_;
    }

    public void setFuncDeclArg(List<?> list)
    {
        for(PFuncDeclArg e : this._funcDeclArg_)
        {
            e.parent(null);
        }
        this._funcDeclArg_.clear();

        for(Object obj_e : list)
        {
            PFuncDeclArg e = (PFuncDeclArg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._funcDeclArg_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcDeclArg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcDeclArg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PFuncDeclArg> i = this._funcDeclArg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFuncDeclArg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
