/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import java.util.*;
import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AIfStatement extends PStatement
{
    private final LinkedList<PIfSegment> _ifSegment_ = new LinkedList<PIfSegment>();

    public AIfStatement()
    {
        // Constructor
    }

    public AIfStatement(
        @SuppressWarnings("hiding") List<?> _ifSegment_)
    {
        // Constructor
        setIfSegment(_ifSegment_);

    }

    @Override
    public Object clone()
    {
        return new AIfStatement(
            cloneList(this._ifSegment_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStatement(this);
    }

    public LinkedList<PIfSegment> getIfSegment()
    {
        return this._ifSegment_;
    }

    public void setIfSegment(List<?> list)
    {
        for(PIfSegment e : this._ifSegment_)
        {
            e.parent(null);
        }
        this._ifSegment_.clear();

        for(Object obj_e : list)
        {
            PIfSegment e = (PIfSegment) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._ifSegment_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifSegment_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifSegment_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PIfSegment> i = this._ifSegment_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIfSegment) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
