/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import java.util.*;
import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PTypeDecl> _customTypes_ = new LinkedList<PTypeDecl>();
    private final LinkedList<PFuncDecl> _functions_ = new LinkedList<PFuncDecl>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _customTypes_,
        @SuppressWarnings("hiding") List<?> _functions_)
    {
        // Constructor
        setCustomTypes(_customTypes_);

        setFunctions(_functions_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._customTypes_),
            cloneList(this._functions_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PTypeDecl> getCustomTypes()
    {
        return this._customTypes_;
    }

    public void setCustomTypes(List<?> list)
    {
        for(PTypeDecl e : this._customTypes_)
        {
            e.parent(null);
        }
        this._customTypes_.clear();

        for(Object obj_e : list)
        {
            PTypeDecl e = (PTypeDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._customTypes_.add(e);
        }
    }

    public LinkedList<PFuncDecl> getFunctions()
    {
        return this._functions_;
    }

    public void setFunctions(List<?> list)
    {
        for(PFuncDecl e : this._functions_)
        {
            e.parent(null);
        }
        this._functions_.clear();

        for(Object obj_e : list)
        {
            PFuncDecl e = (PFuncDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._functions_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._customTypes_)
            + toString(this._functions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._customTypes_.remove(child))
        {
            return;
        }

        if(this._functions_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PTypeDecl> i = this._customTypes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTypeDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PFuncDecl> i = this._functions_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFuncDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
