/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import java.util.*;
import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class ATypeDeclFieldList extends PTypeDeclFieldList
{
    private final LinkedList<PTypeDeclField> _typeDeclField_ = new LinkedList<PTypeDeclField>();

    public ATypeDeclFieldList()
    {
        // Constructor
    }

    public ATypeDeclFieldList(
        @SuppressWarnings("hiding") List<?> _typeDeclField_)
    {
        // Constructor
        setTypeDeclField(_typeDeclField_);

    }

    @Override
    public Object clone()
    {
        return new ATypeDeclFieldList(
            cloneList(this._typeDeclField_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeDeclFieldList(this);
    }

    public LinkedList<PTypeDeclField> getTypeDeclField()
    {
        return this._typeDeclField_;
    }

    public void setTypeDeclField(List<?> list)
    {
        for(PTypeDeclField e : this._typeDeclField_)
        {
            e.parent(null);
        }
        this._typeDeclField_.clear();

        for(Object obj_e : list)
        {
            PTypeDeclField e = (PTypeDeclField) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._typeDeclField_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeDeclField_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeDeclField_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PTypeDeclField> i = this._typeDeclField_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTypeDeclField) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
