/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class TKwEndif extends Token
{
    public TKwEndif()
    {
        super.setText("endif");
    }

    public TKwEndif(int line, int pos)
    {
        super.setText("endif");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwEndif(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwEndif(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwEndif text.");
    }
}
