/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class TKwEndfunc extends Token
{
    public TKwEndfunc()
    {
        super.setText("endfunc");
    }

    public TKwEndfunc(int line, int pos)
    {
        super.setText("endfunc");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwEndfunc(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwEndfunc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwEndfunc text.");
    }
}
