/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class TKwEndblock extends Token
{
    public TKwEndblock()
    {
        super.setText("endblock");
    }

    public TKwEndblock(int line, int pos)
    {
        super.setText("endblock");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwEndblock(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwEndblock(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwEndblock text.");
    }
}
