/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class TKwNew extends Token
{
    public TKwNew()
    {
        super.setText("new");
    }

    public TKwNew(int line, int pos)
    {
        super.setText("new");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwNew(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwNew(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwNew text.");
    }
}
