/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class ADeclarationStatement extends PStatement
{
    private PVarDeclType _varDeclType_;
    private PVarDeclName _varDeclName_;

    public ADeclarationStatement()
    {
        // Constructor
    }

    public ADeclarationStatement(
        @SuppressWarnings("hiding") PVarDeclType _varDeclType_,
        @SuppressWarnings("hiding") PVarDeclName _varDeclName_)
    {
        // Constructor
        setVarDeclType(_varDeclType_);

        setVarDeclName(_varDeclName_);

    }

    @Override
    public Object clone()
    {
        return new ADeclarationStatement(
            cloneNode(this._varDeclType_),
            cloneNode(this._varDeclName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarationStatement(this);
    }

    public PVarDeclType getVarDeclType()
    {
        return this._varDeclType_;
    }

    public void setVarDeclType(PVarDeclType node)
    {
        if(this._varDeclType_ != null)
        {
            this._varDeclType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclType_ = node;
    }

    public PVarDeclName getVarDeclName()
    {
        return this._varDeclName_;
    }

    public void setVarDeclName(PVarDeclName node)
    {
        if(this._varDeclName_ != null)
        {
            this._varDeclName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDeclType_)
            + toString(this._varDeclName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDeclType_ == child)
        {
            this._varDeclType_ = null;
            return;
        }

        if(this._varDeclName_ == child)
        {
            this._varDeclName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDeclType_ == oldChild)
        {
            setVarDeclType((PVarDeclType) newChild);
            return;
        }

        if(this._varDeclName_ == oldChild)
        {
            setVarDeclName((PVarDeclName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
