/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncArgDecl extends PFuncArgDecl
{
    private PFuncArgDeclType _funcArgDeclType_;
    private PFuncArgDeclName _funcArgDeclName_;

    public AFuncArgDecl()
    {
        // Constructor
    }

    public AFuncArgDecl(
        @SuppressWarnings("hiding") PFuncArgDeclType _funcArgDeclType_,
        @SuppressWarnings("hiding") PFuncArgDeclName _funcArgDeclName_)
    {
        // Constructor
        setFuncArgDeclType(_funcArgDeclType_);

        setFuncArgDeclName(_funcArgDeclName_);

    }

    @Override
    public Object clone()
    {
        return new AFuncArgDecl(
            cloneNode(this._funcArgDeclType_),
            cloneNode(this._funcArgDeclName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncArgDecl(this);
    }

    public PFuncArgDeclType getFuncArgDeclType()
    {
        return this._funcArgDeclType_;
    }

    public void setFuncArgDeclType(PFuncArgDeclType node)
    {
        if(this._funcArgDeclType_ != null)
        {
            this._funcArgDeclType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcArgDeclType_ = node;
    }

    public PFuncArgDeclName getFuncArgDeclName()
    {
        return this._funcArgDeclName_;
    }

    public void setFuncArgDeclName(PFuncArgDeclName node)
    {
        if(this._funcArgDeclName_ != null)
        {
            this._funcArgDeclName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcArgDeclName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcArgDeclType_)
            + toString(this._funcArgDeclName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcArgDeclType_ == child)
        {
            this._funcArgDeclType_ = null;
            return;
        }

        if(this._funcArgDeclName_ == child)
        {
            this._funcArgDeclName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcArgDeclType_ == oldChild)
        {
            setFuncArgDeclType((PFuncArgDeclType) newChild);
            return;
        }

        if(this._funcArgDeclName_ == oldChild)
        {
            setFuncArgDeclName((PFuncArgDeclName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
