/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncDeclArg extends PFuncDeclArg
{
    private PFuncDeclArgType _funcDeclArgType_;
    private PFuncDeclArgName _funcDeclArgName_;

    public AFuncDeclArg()
    {
        // Constructor
    }

    public AFuncDeclArg(
        @SuppressWarnings("hiding") PFuncDeclArgType _funcDeclArgType_,
        @SuppressWarnings("hiding") PFuncDeclArgName _funcDeclArgName_)
    {
        // Constructor
        setFuncDeclArgType(_funcDeclArgType_);

        setFuncDeclArgName(_funcDeclArgName_);

    }

    @Override
    public Object clone()
    {
        return new AFuncDeclArg(
            cloneNode(this._funcDeclArgType_),
            cloneNode(this._funcDeclArgName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncDeclArg(this);
    }

    public PFuncDeclArgType getFuncDeclArgType()
    {
        return this._funcDeclArgType_;
    }

    public void setFuncDeclArgType(PFuncDeclArgType node)
    {
        if(this._funcDeclArgType_ != null)
        {
            this._funcDeclArgType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDeclArgType_ = node;
    }

    public PFuncDeclArgName getFuncDeclArgName()
    {
        return this._funcDeclArgName_;
    }

    public void setFuncDeclArgName(PFuncDeclArgName node)
    {
        if(this._funcDeclArgName_ != null)
        {
            this._funcDeclArgName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDeclArgName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcDeclArgType_)
            + toString(this._funcDeclArgName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcDeclArgType_ == child)
        {
            this._funcDeclArgType_ = null;
            return;
        }

        if(this._funcDeclArgName_ == child)
        {
            this._funcDeclArgName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcDeclArgType_ == oldChild)
        {
            setFuncDeclArgType((PFuncDeclArgType) newChild);
            return;
        }

        if(this._funcDeclArgName_ == oldChild)
        {
            setFuncDeclArgName((PFuncDeclArgName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
