/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplyExpr extends PExpr
{
    private PIntLit _op1_;
    private PIntLit _op2_;

    public AMultiplyExpr()
    {
        // Constructor
    }

    public AMultiplyExpr(
        @SuppressWarnings("hiding") PIntLit _op1_,
        @SuppressWarnings("hiding") PIntLit _op2_)
    {
        // Constructor
        setOp1(_op1_);

        setOp2(_op2_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplyExpr(
            cloneNode(this._op1_),
            cloneNode(this._op2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplyExpr(this);
    }

    public PIntLit getOp1()
    {
        return this._op1_;
    }

    public void setOp1(PIntLit node)
    {
        if(this._op1_ != null)
        {
            this._op1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op1_ = node;
    }

    public PIntLit getOp2()
    {
        return this._op2_;
    }

    public void setOp2(PIntLit node)
    {
        if(this._op2_ != null)
        {
            this._op2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._op1_)
            + toString(this._op2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._op1_ == child)
        {
            this._op1_ = null;
            return;
        }

        if(this._op2_ == child)
        {
            this._op2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._op1_ == oldChild)
        {
            setOp1((PIntLit) newChild);
            return;
        }

        if(this._op2_ == oldChild)
        {
            setOp2((PIntLit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
