/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class ATypeDecl extends PTypeDecl
{
    private PTypeDeclName _typeDeclName_;
    private PTypeDeclFieldList _typeDeclFieldList_;

    public ATypeDecl()
    {
        // Constructor
    }

    public ATypeDecl(
        @SuppressWarnings("hiding") PTypeDeclName _typeDeclName_,
        @SuppressWarnings("hiding") PTypeDeclFieldList _typeDeclFieldList_)
    {
        // Constructor
        setTypeDeclName(_typeDeclName_);

        setTypeDeclFieldList(_typeDeclFieldList_);

    }

    @Override
    public Object clone()
    {
        return new ATypeDecl(
            cloneNode(this._typeDeclName_),
            cloneNode(this._typeDeclFieldList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeDecl(this);
    }

    public PTypeDeclName getTypeDeclName()
    {
        return this._typeDeclName_;
    }

    public void setTypeDeclName(PTypeDeclName node)
    {
        if(this._typeDeclName_ != null)
        {
            this._typeDeclName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDeclName_ = node;
    }

    public PTypeDeclFieldList getTypeDeclFieldList()
    {
        return this._typeDeclFieldList_;
    }

    public void setTypeDeclFieldList(PTypeDeclFieldList node)
    {
        if(this._typeDeclFieldList_ != null)
        {
            this._typeDeclFieldList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDeclFieldList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeDeclName_)
            + toString(this._typeDeclFieldList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeDeclName_ == child)
        {
            this._typeDeclName_ = null;
            return;
        }

        if(this._typeDeclFieldList_ == child)
        {
            this._typeDeclFieldList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeDeclName_ == oldChild)
        {
            setTypeDeclName((PTypeDeclName) newChild);
            return;
        }

        if(this._typeDeclFieldList_ == oldChild)
        {
            setTypeDeclFieldList((PTypeDeclFieldList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
