/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class AVarFetchExpr extends PExpr
{
    private PVarFetchName _varFetchName_;

    public AVarFetchExpr()
    {
        // Constructor
    }

    public AVarFetchExpr(
        @SuppressWarnings("hiding") PVarFetchName _varFetchName_)
    {
        // Constructor
        setVarFetchName(_varFetchName_);

    }

    @Override
    public Object clone()
    {
        return new AVarFetchExpr(
            cloneNode(this._varFetchName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarFetchExpr(this);
    }

    public PVarFetchName getVarFetchName()
    {
        return this._varFetchName_;
    }

    public void setVarFetchName(PVarFetchName node)
    {
        if(this._varFetchName_ != null)
        {
            this._varFetchName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varFetchName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varFetchName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varFetchName_ == child)
        {
            this._varFetchName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varFetchName_ == oldChild)
        {
            setVarFetchName((PVarFetchName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
