/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

public abstract class PNewVarInitFieldList extends Node
{
    // Empty body
}
