/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.linguate.arboratecompiler.node;

import org.linguate.arboratecompiler.analysis.*;

@SuppressWarnings("nls")
public final class TKwType extends Token
{
    public TKwType()
    {
        super.setText("type");
    }

    public TKwType(int line, int pos)
    {
        super.setText("type");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwType(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwType(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwType text.");
    }
}
